### ISSUE TITLE
ENOENT when editing .c files

### ISSUE THREAD

**Issue by HotelCalifornia** [purduesigbots/pros-atom#19]
> ...After I created a new PROS project, each time I click on a ".c" file, it gives me an ENOENT error. Is there a way to fix this?

Stacktrace:

    Uncaught Error: ENOENT: no such file or directory, stat 'arm-none-eabi-g++' fs.js:992

    Error: ENOENT: no such file or directory, stat 'arm-none-eabi-g++'
        at Error (native)
        at fs.statSync (fs.js:992:18)
        at Object.fs.statSync (ELECTRON_ASAR.js:275:16)
        at /Users/myname/.atom/packages/pros/lib/lint.coffee:53:38
        at /Users/myname/.atom/packages/pros/node_modules/command-exists/lib/command-exists.js:12:13
        at ChildProcess.exithandler (child_process.js:225:5)
        at emitTwo (events.js:106:13)
        at ChildProcess.emit (events.js:191:7)
        at maybeClose (internal/child_process.js:877:16)
        at Socket. (internal/child_process.js:334:11)
        at emitOne (events.js:96:13)
        at Socket.emit (events.js:188:7)
        at Pipe._handle.close [as _onclose] (net.js:493:12)

(migrated from #17)

**Comment by HotelCalifornia** [comment]
Per @jwalk511:

> Just seeing that this involves lint.coffee, I think this is probably solved by downloading Xcode from the app store, and then running it at least once.
> Just as a sanity check, you should be able to open Terminal and run arm-none-eabi-g++, and get arm-none-eabi-g++: fatal error: no input files compilation terminated. in response.

**Comment by HotelCalifornia** [comment]
Closing due to lack of response
