### ISSUE TITLE
Uncaught ReferenceError: command is not defined

### ISSUE THREAD

**Issue by Marsgate** [purduesigbots/pros-atom#32]
[Enter steps to reproduce:]

1. I start atom.
2. Upload to the cortex successfully.
3. Every subsequent attempt to upload results in this error.
4. I have to restart atom to upload again.

**Atom**: 1.14.3 ia32
**Electron**: 1.3.13
**OS**: Microsoft Windows 10 Education
**Thrown From**: [pros](https://github.com/purduesigbots/pros-atom) package 0.6.3

### Stack Trace

Uncaught ReferenceError: command is not defined

```
At C:\Users\Micah-PC\.atom\packages\pros\lib\proscli.coffee:146

ReferenceError: command is not defined
    at Object.executeInTerminal (/packages/pros/lib/proscli.coffee:146:41)
    at Object.uploadProject (/packages/pros/lib/main.coffee:141:11)
    at /packages/pros/lib/main.coffee:66:70)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/app.asar/src/command-registry.js:259:29)
    at CommandRegistry.handleCommandEvent (/app.asar/src/command-registry.js:3:59)
    at CommandRegistry.module.exports.CommandRegistry.dispatch (/app.asar/src/command-registry.js:160:19)
    at executeCallback (/packages/tool-bar/lib/tool-bar-button-view.js:105:19)
    at ToolBarButtonView._onClick (/packages/tool-bar/lib/tool-bar-button-view.js:69:7)
```

### Commands

```
     -1:26.5.0 tree-view:show (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
     -1:23.1.0 PROS:Toggle-Terminal (input.hidden-input)
  2x -1:03.7.0 PROS:Upload-Project (input.hidden-input)
```

### Non-Core Packages

```
build 0.67.0 
busy 0.7.0 
file-icons 2.0.15 
linter 1.11.23 
platformio-ide-terminal 2.2.3 
pros 0.6.3 
tool-bar 1.0.1 
tool-bar-main 0.0.10 
```

**Comment by HotelCalifornia** [comment]
fixed in #33
