### ISSUE TITLE
Uncaught TypeError: Path must be a string. Received undefined

### ISSUE THREAD

**Issue by evanc1648** [purduesigbots/pros-atom#54]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.21.2 x64
**Electron**: 1.6.15
**OS**: Microsoft Windows 10 Home
**Thrown From**: [pros](https://github.com/purduesigbots/pros-atom) package 0.7.4

### Stack Trace

Uncaught TypeError: Path must be a string. Received undefined

```
At path.js:7

TypeError: Path must be a string. Received undefined
    at assertPath (path.js:7:11)
    at Object.join (path.js:468:7)
    at /packages/pros/lib/lint.coffee:59:31
    at /packages/pros/node_modules/command-exists/lib/command-exists.js:67:9
    at ChildProcess.exithandler (child_process.js:230:5)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:885:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
```

### Commands

```
  5x -0:35.4.0 core:backspace (input.hidden-input)
```

### Non-Core Packages

```
build 0.69.0 
busy 0.7.0 
busy-signal 1.4.3 
intentions 1.1.5 
linter 2.2.0 
linter-ui-default 1.6.10 
platformio-ide-terminal 2.7.0 
pros 0.7.4 
tool-bar 1.1.0 
tool-bar-main 0.0.10 
```

**Comment by HotelCalifornia** [comment]
Can you tell us what you were doing when this happened?
